const sources = {
"ars technica":{},
"the verge":{},
"kotaku":{},
"macrumors":{},
"ewrestlingnews":{},
"gizmodo.com":{},
"polygon":{},
"pinkbike.com":{},
"xda developers":{},
"lifehacker.com":{},
"bungie.net":{},
"cnn":{},
"9to5google.com":{},
"ign":{},
"youtube":{},
"live science":{},
"scitechdaily":{},
"spacenews":{},
"the guardian":{},
"space.com":{},
"phys.org":{},
"the hill":{},
"cnet":{},
"daily mail":{},
"nature.com":{},
"wsb atlanta":{},
"townhall":{},
"eatthis.com":{},
"sciencealert":{},
"bnonews.com":{},
"deseret news":{},
"the lancet":{},
"abc news":{},
"neurosciencenews.com":{},
"ktvi fox 2 st. louis":{},
"new york post":{},
"financial times":{},
"ksbw the central coast":{},
"new york times":{},
"the washington post":{},
"espn":{},
"cbs news":{},
"fox news":{},
"wls-tv":{},
"cnbc":{},
"variety":{},
"usa today":{},
"fox business":{},
"toofab":{},
"tmz":{},
"mlive.com":{},
"grub street":{},
"page six":{},
"deadline":{},
"hollywood reporter":{},
"vulture":{},
"the a.v. club":{},
"tvline":{},
"eonline.com":{},
"goheels.com":{},
"the boston globe":{},
"u.s. soccer":{},
"the falcoholic":{},
"cincy jungle":{},
"prideofdetroit.com":{},
"mlb trade rumors":{},
"syracuse.com":{},
"reuters":{},
"the wall street journal":{},
"business insider":{},
"jalopnik":{},
"kitco news":{},
"marketwatch":{},
"yahoo entertainment":{},
"chicago tribune" :{},
}

export default sources;
