const sources = {
  "ars technica": { establisedIn: "", viewers: 0, summary: "" },
  "the verge": { establisedIn: "", viewers: 0, summary: "" },
  kotaku: { establisedIn: "", viewers: 0, summary: "" },
  macrumors: { establisedIn: "", viewers: 0, summary: "" },
  ewrestlingnews: { establisedIn: "", viewers: 0, summary: "" },
  "gizmodo.com": { establisedIn: "", viewers: 0, summary: "" },
  polygon: { establisedIn: "", viewers: 0, summary: "" },
  "pinkbike.com": { establisedIn: "", viewers: 0, summary: "" },
  "xda developers": { establisedIn: "", viewers: 0, summary: "" },
  "lifehacker.com": { establisedIn: "", viewers: 0, summary: "" },
  "bungie.net": { establisedIn: "", viewers: 0, summary: "" },
  cnn: { establisedIn: "", viewers: 0, summary: "" },
  "9to5google.com": { establisedIn: "", viewers: 0, summary: "" },
  ign: { establisedIn: "", viewers: 0, summary: "" },
  youtube: { establisedIn: "", viewers: 0, summary: "" },
  "live science": { establisedIn: "", viewers: 0, summary: "" },
  scitechdaily: { establisedIn: "", viewers: 0, summary: "" },
  spacenews: { establisedIn: "", viewers: 0, summary: "" },
  "the guardian": { establisedIn: "", viewers: 0, summary: "" },
  "space.com": { establisedIn: "", viewers: 0, summary: "" },
  "phys.org": { establisedIn: "", viewers: 0, summary: "" },
  "the hill": { establisedIn: "", viewers: 0, summary: "" },
  cnet: { establisedIn: "", viewers: 0, summary: "" },
  "daily mail": { establisedIn: "", viewers: 0, summary: "" },
  "nature.com": { establisedIn: "", viewers: 0, summary: "" },
  "wsb atlanta": { establisedIn: "", viewers: 0, summary: "" },
  townhall: { establisedIn: "", viewers: 0, summary: "" },
  "eatthis.com": { establisedIn: "", viewers: 0, summary: "" },
  sciencealert: { establisedIn: "", viewers: 0, summary: "" },
  "bnonews.com": { establisedIn: "", viewers: 0, summary: "" },
  "deseret news": { establisedIn: "", viewers: 0, summary: "" },
  "the lancet": { establisedIn: "", viewers: 0, summary: "" },
  "abc news": { establisedIn: "", viewers: 0, summary: "" },
  "neurosciencenews.com": { establisedIn: "", viewers: 0, summary: "" },
  "ktvi fox 2 st. louis": { establisedIn: "", viewers: 0, summary: "" },
  "new york post": { establisedIn: "", viewers: 0, summary: "" },
  "financial times": { establisedIn: "", viewers: 0, summary: "" },
  "ksbw the central coast": { establisedIn: "", viewers: 0, summary: "" },
  "new york times": { establisedIn: "", viewers: 0, summary: "" },
  "the washington post": { establisedIn: "", viewers: 0, summary: "" },
  espn: { establisedIn: "", viewers: 0, summary: "" },
  "cbs news": { establisedIn: "", viewers: 0, summary: "" },
  "fox news": { establisedIn: "", viewers: 0, summary: "" },
  "wls-tv": { establisedIn: "", viewers: 0, summary: "" },
  cnbc: { establisedIn: "", viewers: 0, summary: "" },
  variety: { establisedIn: "", viewers: 0, summary: "" },
  "usa today": { establisedIn: "", viewers: 0, summary: "" },
  "fox business": { establisedIn: "", viewers: 0, summary: "" },
  toofab: { establisedIn: "", viewers: 0, summary: "" },
  tmz: { establisedIn: "", viewers: 0, summary: "" },
  "mlive.com": { establisedIn: "", viewers: 0, summary: "" },
  "grub street": { establisedIn: "", viewers: 0, summary: "" },
  "page six": { establisedIn: "", viewers: 0, summary: "" },
  deadline: { establisedIn: "", viewers: 0, summary: "" },
  "hollywood reporter": { establisedIn: "", viewers: 0, summary: "" },
  vulture: { establisedIn: "", viewers: 0, summary: "" },
  "the a.v. club": { establisedIn: "", viewers: 0, summary: "" },
  tvline: { establisedIn: "", viewers: 0, summary: "" },
  "eonline.com": { establisedIn: "", viewers: 0, summary: "" },
  "goheels.com": { establisedIn: "", viewers: 0, summary: "" },
  "the boston globe": { establisedIn: "", viewers: 0, summary: "" },
  "u.s. soccer": { establisedIn: "", viewers: 0, summary: "" },
  "the falcoholic": { establisedIn: "", viewers: 0, summary: "" },
  "cincy jungle": { establisedIn: "", viewers: 0, summary: "" },
  "prideofdetroit.com": { establisedIn: "", viewers: 0, summary: "" },
  "mlb trade rumors": { establisedIn: "", viewers: 0, summary: "" },
  "syracuse.com": { establisedIn: "", viewers: 0, summary: "" },
  reuters: { establisedIn: "", viewers: 0, summary: "" },
  "the wall street journal": { establisedIn: "", viewers: 0, summary: "" },
  "business insider": { establisedIn: "", viewers: 0, summary: "" },
  jalopnik: { establisedIn: "", viewers: 0, summary: "" },
  "kitco news": { establisedIn: "", viewers: 0, summary: "" },
  marketwatch: { establisedIn: "", viewers: 0, summary: "" },
  "yahoo entertainment": { establisedIn: "", viewers: 0, summary: "" },
  "chicago tribune": { establisedIn: "", viewers: 0, summary: "" },
};

export default sources;
